/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function up(knex) {
    return knex.raw(`
  CREATE SEQUENCE wage_subsidy_applications_id_seq;

  CREATE TABLE WAGE_SUBSIDY_APPLICATIONS (
      id integer NOT NULL DEFAULT nextval('wage_subsidy_applications_id_seq'::regclass),
      title character varying(255),
      catchmentno integer,
      formtype character varying(255) COLLATE pg_catalog."default",
      applicationid character varying(255) COLLATE pg_catalog."default",
      applicationstatus character varying(255) COLLATE pg_catalog."default",
      operatingname character varying(255) COLLATE pg_catalog."default",
      businessnumber character varying(255) COLLATE pg_catalog."default",
      businessaddress1 character varying(255) COLLATE pg_catalog."default",
      businesscity character varying(255) COLLATE pg_catalog."default",
      businessprovince character varying(2) COLLATE pg_catalog."default",
      businesspostal character varying(7) COLLATE pg_catalog."default",
      businessphone character varying(12) COLLATE pg_catalog."default",
      businessfax character varying(255) COLLATE pg_catalog."default",
      businessemail character varying(255) COLLATE pg_catalog."default",
      otherworkaddress boolean,
      sectortype character varying(255) COLLATE pg_catalog."default",
      typeofindustry character varying(255) COLLATE pg_catalog."default",
      organizationsize character varying(255) COLLATE pg_catalog."default",
      cewsandorcrhp character varying(255) COLLATE pg_catalog."default",
      employeedisplacement boolean,
      labourdispute boolean,
      unionconcurrence character varying(255) COLLATE pg_catalog."default",
      liabilitycoverage boolean,
      wagesubsidy boolean,
      wsbccoverage boolean,
      lawcomplianceconsent boolean,
      orgeligibilityconsent boolean,
      wsbcnumber character varying(255) COLLATE pg_catalog."default",
      addressalt character varying(255) COLLATE pg_catalog."default",
      cityalt character varying(255) COLLATE pg_catalog."default",
      provincealt character varying(2) COLLATE pg_catalog."default",
      postalalt character varying(7) COLLATE pg_catalog."default",
      participantemail0 character varying(255) COLLATE pg_catalog."default",
      participantemail1 character varying(255) COLLATE pg_catalog."default",
      participantemail2 character varying(255) COLLATE pg_catalog."default",
      participantemail3 character varying(255) COLLATE pg_catalog."default",
      participantemail4 character varying(255) COLLATE pg_catalog."default",
      positiontitle0 character varying(255) COLLATE pg_catalog."default",
      numberofpositions0 integer,
      startdate0 date,
      hours0 integer,
      wage0 integer,
      applicationmercs0 integer,
      duties0 text COLLATE pg_catalog."default",
      skills0 text COLLATE pg_catalog."default",
      workexperience0 text COLLATE pg_catalog."default",
      positiontitle1 character varying(255) COLLATE pg_catalog."default",
      numberofpositions1 integer,
      startdate1 date,
      hours1 integer,
      wage1 integer,
      applicationmercs1 integer,
      duties1 text COLLATE pg_catalog."default",
      skills1 text COLLATE pg_catalog."default",
      workexperience1 text COLLATE pg_catalog."default",
      signatorytitle character varying(255) COLLATE pg_catalog."default",
      signatory1 character varying(255) COLLATE pg_catalog."default",
      organizationconsent boolean,
      history jsonb,
      sf integer,
      centrename character varying(255) COLLATE pg_catalog."default",
      markedfordeletion boolean,
      internalid character varying(255) COLLATE pg_catalog."default",
      modified date,
      created date,
      status character varying(255) COLLATE pg_catalog."default",
      createdby character varying(255) COLLATE pg_catalog."default",
      createdbyguid character varying(255) COLLATE pg_catalog."default",
      confirmationid character varying(255) COLLATE pg_catalog."default",
      CONSTRAINT wage_subsidy_applications_pkey PRIMARY KEY (id),
      sharedwith varchar(255)
      );
  
  CREATE TABLE Wage_Subsidy_Claim_Form (
      ID SERIAL NOT NULL PRIMARY KEY,
      Title varchar(255),
      CatchmentNo int, 
      FormType varchar(255),
      ApplicationID varchar(255),
      ApplicationStatus varchar(255),
      PeriodStart1 timestamp,
      PeriodStart2 timestamp,
      IsFinalClaim boolean,
      OperatingName varchar(255),
      BusinessAddress1 varchar(255),
      BusinessAddress2 varchar(255),
      BusinessCity varchar(255),
      BusinessPostal varchar(7),
      BusinessPhone varchar(12),
      EmployeeFirstName varchar(255),
      EmployeeLastName varchar(255),
      DateFrom1 date,
      DateFrom2 date,
      DateFrom3 date,
      DateFrom4 date,
      DateFrom5 date,
      DateTo1 date,
      DateTo2 date,
      DateTo3 date,
      DateTo4 date,
      DateTo5 date,
      HoursWorked1 int,
      HoursWorked2 int,
      HoursWorked3 int,
      HoursWorked4 int,
      HoursWorked5 int,
      HourlyWage1 int,
      HourlyWage2 int,
      HourlyWage3 int,
      HourlyWage4 int,
      HourlyWage5 int,
      WorkActivitiesAndIssues text,
      TotalWage1 int,
      TotalWage2 int,
      TotalWage3 int,
      TotalWage4 int,
      TotalWage5 int,
      EligibleWages int,
      EligibleWages2 int,
      TotalMERCs1 int,
      TotalMERCs2 int,
      SubsidyRatePercent1 int,
      SubsidyRatePercent2 int,
      SubsidyRateDateFrom1 date,
      SubsidyRateDateTo1 date,
      TotalAmountReimbursed1 int,
      ClaimApprovedBy1 varchar(255),
      SubsidyRateDateFrom2 date, 
      SubsidyRateDateTo2 date, 
      TotalAmountReimbursed2 int,
      ClaimApprovedBy2 varchar(255),
      ClaimVerifiedDate date,
      TotalSubsidyClaimed int,
      TotalWeeks1 int,
      TotalWeeks2 int,
      WagesReimbursed1 int,
      WagesReimbursed2 int,
      MercsReimbursed1 int,
      MercsReimbursed2 int,
      claimEmployeeInfo jsonb,
      originalApplicationID varchar(10),
      history jsonb,
      SF int,
      centreName varchar(255),
      markedForDeletion boolean,
      internalid varchar(255),
      Modified date,
      Created date,
      status character varying(255) COLLATE pg_catalog."default",
      createdby character varying(255) COLLATE pg_catalog."default",
      createdbyguid character varying(255) COLLATE pg_catalog."default",
      confirmationid character varying(255) COLLATE pg_catalog."default",
      sharedwith varchar(255)
      );


  `)
}

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function down(knex) {
    return knex.raw(`
  DROP TABLE WAGE_SUBSIDY_CLAIM_FORM;
  DROP TABLE WAGE_SUBSIDY_APPLICATIONS;
  DROP SEQUENCE wage_subsidy_applications_id_seq;
  `)
}
