var strings = require("./strings")

module.exports = {
    getHaveEmployeeSubmitted(values){
        var data = [
            `The following information was received:`,
            `<hr />`,
            `<hr />`,
            `<p>Application ID:  ${strings.orEmpty(values._id)}</p>`,
            `<p>Operating Name:  ${strings.orEmpty(values.operatingName)}</p>`,
            `<hr />`,
            `<h5> Business Address Information</h5>`,
            `<p>Business Number:  ${strings.orEmpty(values.businessNumber)}</p>`,
            `<p>Business Address:  ${strings.orEmpty(values.businessAddress)}</p>`,
            `<p>Business City:  ${strings.orEmpty(values.businessCity)}</p>`,
            `<p>Business Province:  ${strings.orEmpty(values.businessProvince)}</p>`,
            `<p>Business Postal:  ${strings.orEmpty(values.businessPostal)}</p>`,
            `<p>Business Email:  ${strings.orEmpty(values.businessEmail)}</p>`,
            `<p>Business Phone:  ${strings.orEmpty(values.businessPhone)}</p>`,
            `<p>Business Fax:  ${strings.orEmpty(values.businessFax)}</p>`,
            `<hr />`,
            `<h5>Alternative Address (only if different from contact)</h5>`,
            `<p>Alternative Address:  ${strings.orEmpty(values.addressAlt)}</p>`,
            `<p>Alternative City:  ${strings.orEmpty(values.cityAlt)}</p>`,
            `<p>Alternative Province:  ${strings.orEmpty(values.provinceAlt)}</p>`,
            `<p>Alternative Postal:  ${strings.orEmpty(values.postalAlt)}</p>`,
            `<hr />`,
            `<h5>Business Questions</h5>`,
            `<p>Sector Type:  ${strings.orEmpty(values.sectorType)}</p>`,
            `<p>Type of Industry:  ${strings.orEmpty(values.typeOfIndustry)}</p>`,
            `<p>Organization Size:  ${strings.orEmpty(values.organizationSize)}</p>`,
            `<p>Actively participating in canada emergency wage subsidy program:  ${strings.orEmpty(values.cewsParticipation)}</p>`,
            `<p>Employee Displacement due to subsidy:  ${strings.orEmpty(values.employeeDisplacement)}</p>`,
            `<p>labour Dispute or stoppage in progress:  ${strings.orEmpty(values.labourDispute)}</p>`,
            `<p>Union Concurrence:  ${strings.orEmpty(values.unionConcurrence)}</p>`,
            `<p>Has 3rd party Liability Coverage:  ${strings.orEmpty(values.liabilityCoverage)}</p>`,
            `<p>Currently receiving WorkBC wage subsidy funding:  ${strings.orEmpty(values.wageSubsidy)}</p>`,
            `<p>Eligibility Confirmed:  ${strings.orEmpty(values.eligibility)}</p>`,
            `<hr />`,
            `<h5>WorkBC Insurance Coverage (only if has coverage)</h5>`,
            `<p>WorkSafeBC Insurance Coverage Number:  ${strings.orEmpty(values.WSBCNumber)}</p>`,
            `<hr />`,
            `<h5>Employee Position 1 </h5>`,
            `<p>Operating Name:  ${strings.orEmpty(values.operatingName0)}</p>`,
            `<p>Number of Positions:  ${strings.orEmpty(values.numberOfPositions0)}</p>`,
            `<p>Employee Email 1:  ${strings.orEmpty(values.position0Email0)}</p>`,
            `<p>Employee Email 2:  ${strings.orEmpty(values.position0Email1)}</p>`,
            `<p>Employee Email 3:  ${strings.orEmpty(values.position0Email2)}</p>`,
            `<p>Employee Email 4:  ${strings.orEmpty(values.position0Email3)}</p>`,
            `<p>Employee Email 5:  ${strings.orEmpty(values.position0Email4)}</p>`,
            `<p>StartDate:  ${strings.orEmpty(values.startDate0)}</p>`,
            `<p>Hours: ${strings.orEmpty(values.hours0)}</p>`,
            `<p>Wage: ${strings.orEmpty(values.wage0)}</p>`,
            `<p>Duties: ${strings.orEmpty(values.duties0)}</p>`,
            `<h5>Employee Position 2 (only if different from above) </h5>`,
            `<p>Operating Name:  ${strings.orEmpty(values.operatingName1)}</p>`,
            `<p>Number of Positions:  ${strings.orEmpty(values.numberOfPositions1)}</p>`,
            `<p>Employee Email 1:  ${strings.orEmpty(values.position1Email0)}</p>`,
            `<p>Employee Email 2:  ${strings.orEmpty(values.position1Email1)}</p>`,
            `<p>Employee Email 3:  ${strings.orEmpty(values.position1Email2)}</p>`,
            `<p>Employee Email 4:  ${strings.orEmpty(values.position1Email3)}</p>`,
            `<p>StartDate:  ${strings.orEmpty(values.startDate0)}</p>`,
            `<p>Hours: ${strings.orEmpty(values.hours1)}</p>`,
            `<p>Wage: ${strings.orEmpty(values.wage1)}</p>`,
            `<p>Duties: ${strings.orEmpty(values.duties1)}</p>`,
            `<hr />                       `,
            `<h5>Signatory names and Organization consent</h5>`,
            `<p>Signatory 1:  ${strings.orEmpty(values.signatory1)}</p>`,
            `<p>Signatory Title:  ${strings.orEmpty(values.signatoryTitle)}</p>`,
            `<p>Organization Consent:  ${strings.orEmpty(values.organizationConsent)}</p>`,
        ]
        return data

    },
    getClaimSubmitted(values){
        var data=[
            ``,
        ]
        return data

    }
}