apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: workbc-wage-subsidy-api
labels:
  template: workbc-wage-subsidy-api
objects:
- apiVersion: v1
  kind: Secret
  type: opaque
  metadata:
    name: ${NAME}-mongodb
  stringData:
    password: ${DATABASE_PASSWORD}
    adminPassword: ${DATABASE_ADMIN_PASSWORD}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DATABASE_SERVICE_NAME}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
          - env:
              - name: MONGODB_USER
                value: ${DATABASE_USER}
              - name: MONGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: ${NAME}-mongodb
              - name: MONGODB_DATABASE
                value: ${DATABASE_NAME}
              - name: MONGODB_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: adminPassword
                    name: ${NAME}-mongodb
            image: ' '
            livenessProbe:
              initialDelaySeconds: 30
              tcpSocket:
                port: 27017
              timeoutSeconds: 1
            name: mongodb
            ports:
              - containerPort: 27017
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - -i
                  - -c
                  - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                    --eval="quit()"
              initialDelaySeconds: 3
              timeoutSeconds: 1
            resources:
              limits:
                memory: ${MEMORY_MONGODB_LIMIT}
            volumeMounts:
              - mountPath: /var/lib/mongodb/data
                name: ${DATABASE_SERVICE_NAME}-data
        volumes:
          - name: ${DATABASE_SERVICE_NAME}-data
            persistentVolumeClaim:
              claimName: ${DATABASE_SERVICE_NAME}
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - mongodb
          from:
            kind: ImageStreamTag
            name: mongodb:3.6
            namespace: openshift
        type: ImageChange
      - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
      - name: ${DATABASE_SERVICE_NAME}
        port: 27017
        targetPort: 27017
    selector:
        name: ${DATABASE_SERVICE_NAME}
- apiVersion: v1
  kind: Secret
  type: opaque
  metadata:
    name: ${NAME}-list
  stringData:
    username: ${OPENSHIFT_NODEJS_LISTUSER}
    password: ${OPENSHIFT_NODEJS_LISTPASS}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}:${TAG}
          name: workbc-wage-subsidy-api
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          env:
          - name: OPENSHIFT_NODEJS_ORIGIN_URL
            value: ${OPENSHIFT_NODEJS_ORIGIN_URL}
          - name: OPENSHIFT_NODEJS_CONFIRMATIONONE
            value: ${OPENSHIFT_NODEJS_CONFIRMATIONONE}
          - name: OPENSHIFT_NODEJS_CONFIRMATIONTWO
            value: ${OPENSHIFT_NODEJS_CONFIRMATIONTWO}
          - name: OPENSHIFT_NODEJS_CONFIRMATIONBCC
            value: ${OPENSHIFT_NODEJS_CONFIRMATIONBCC}
          - name: OPENSHIFT_NODEJS_PARTICIPANTEMAIL
            value: ${OPENSHIFT_NODEJS_PARTICIPANTEMAIL}
          - name: OPENSHIFT_NODEJS_LISTEMAIL
            value: ${OPENSHIFT_NODEJS_LISTEMAIL}
          - name: OPENSHIFT_NODEJS_NOTIFYEMAIL
            value: ${OPENSHIFT_NODEJS_NOTIFYEMAIL}
          - name: OPENSHIFT_NODEJS_CLIENTURL
            value: ${OPENSHIFT_NODEJS_CLIENTURL}
          - name: OPENSHIFT_NODEJS_LISTWEBURL
            value: ${OPENSHIFT_NODEJS_LISTWEBURL}
          - name: OPENSHIFT_NODEJS_LISTUSER
            valueFrom:
              secretKeyRef:
                key: username
                name: ${NAME}-list
          - name: OPENSHIFT_NODEJS_LISTPASS
            valueFrom:
              secretKeyRef:
                key: password
                name: ${NAME}-list
          - name: OPENSHIFT_NODEJS_LISTDOMAIN
            value: ${OPENSHIFT_NODEJS_LISTDOMAIN}
          - name: OPENSHIFT_NODEJS_LISTPARTY
            value: ${OPENSHIFT_NODEJS_LISTPARTY}
          - name: OPENSHIFT_NODEJS_LISTADFS
            value: ${OPENSHIFT_NODEJS_LISTADFS}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - workbc-wage-subsidy-api
        from:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
parameters:
- description: Database service name
  name: DATABASE_SERVICE_NAME
  value: workbc-wage-subsidy-mongodb
- description: Username for MongoDB user that will be used for accessing the database
  from: user[A-Z0-9]{3}
  generate: expression
  name: DATABASE_USER
- description: Password for the MongoDB user
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_PASSWORD
- description: Database name
  name: DATABASE_NAME
  value: workbc-wage-subsidy
- description: Password for the database admin user
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_ADMIN_PASSWORD
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Maximum amount of memory the MongoDB container can use.
  displayName: Memory Limit (MongoDB)
  name: MEMORY_MONGODB_LIMIT
  required: true
  value: 1Gi
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: workbc-wage-subsidy-api
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ''
- description: Tag used for the image tags
  displayName: tag
  name: TAG
  required: true
  value: latest
- description: Email one to send confirmation emails (test)
  displayName: Confirmation email one
  name: OPENSHIFT_NODEJS_CONFIRMATIONONE
  required: false
  value: ''
- description: Email two to send confirmation emails (test)
  displayName: Confirmation email two
  name: OPENSHIFT_NODEJS_CONFIRMATIONTWO
  required: false
  value: ''
- description: BCC email to send confirmation emails
  displayName: Confirmation BCC email
  name: OPENSHIFT_NODEJS_CONFIRMATIONBCC
  required: false
  value: ''
- description: List email to send notification emails
  displayName: List email
  name: OPENSHIFT_NODEJS_LISTEMAIL
  required: false
  value: ''
- description: Notify email to send notification emails
  displayName: Notify email
  name: OPENSHIFT_NODEJS_NOTIFYEMAIL
  required: false
  value: ''
- description: The origin URL
  displayName: workbc-wage-subsidy api
  name: OPENSHIFT_NODEJS_ORIGIN_URL
  required: false
  value: ''
- description: URL for email
  displayName: Client URL
  name: OPENSHIFT_NODEJS_CLIENTURL
  required: false
  value: ''
- description: List Web URL
  displayName: List Web URL
  name: OPENSHIFT_NODEJS_LISTWEBURL
  required: true
  value: ''
- description: List User
  displayName: List User
  name: OPENSHIFT_NODEJS_LISTUSER
  required: true
  value: ''
- description: List Pass
  displayName: List Pass
  name: OPENSHIFT_NODEJS_LISTPASS
  required: true
  value: ''
- description: List Domain
  displayName: List Domain
  name: OPENSHIFT_NODEJS_LISTDOMAIN
  required: true
  value: ''
- description: List Party
  displayName: List Party
  name: OPENSHIFT_NODEJS_LISTPARTY
  required: true
  value: ''
- description: List ADFS
  displayName: List ADFS
  name: OPENSHIFT_NODEJS_LISTADFS
  required: true
  value: ''
- description: The namespace of the OS project containing the imagestreams
  displayName: Image Namespace
  name: IMAGE_NAMESPACE
  required: true
  value: myproject-tools