

# This is a basic workflow that will start a build with every push


name: CI/CD Runtests and build on Dev


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches: [ dev ]
    paths-ignore:
        - '.github/workflows/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        imagename: ["workbc-wage-subsidy-v2-static","workbc-wage-subsidy-v2-admin-api"]
        include:
          - imagename: "workbc-wage-subsidy-v2-static"
            context: "./packages/static"
          - imagename: "workbc-wage-subsidy-v2-admin-api"
            context: "./packages/admin-api"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: "Read dockerignore admin api contents"
        uses: andstor/file-reader-action@v1
        with:
          path: "./packages/admin-api/.dockerignore"
      - run: npm install
      - run: npm test
      - name: Install oc v3
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 3
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: ${{secrets.OCP4_SERVER_URL}}

          # Authentication Token. Can use username and password instead.
          # Refer to Step 3.
          openshift_token: ${{ secrets.API_TOKEN_4 }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: true

          # Optional - this sets your Kubernetes context's current namespace after logging in.
          namespace: ${{secrets.PROJECT_TOOLS_4}}
      #static openshift
      - name: Build for pushing static image to OpenShift registry
        id: build-static-image-os
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.imagename }}
          tags: latest
          context: ${{ matrix.context }}
          containerfiles: ${{ matrix.context }}/Dockerfile
          tls-verify: false
          build-args: VITE_REACT_ENVIRONMENT=Dev
      - name: Build for pushing static image to OpenShift registry
        id: build-static-image-docker
        uses: redhat-actions/buildah-build@v2
        with:
          image: elmsd/${{ matrix.imagename }}
          tags: latest
          context: ${{ matrix.context }}
          containerfiles: ${{ matrix.context }}/Dockerfile
          tls-verify: false
          build-args: VITE_REACT_ENVIRONMENT=Dev
      - name: Push Static To OpenShift Image repo
        id: push-to-os-static
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-static-image-os.outputs.image }}
          tags: ${{ steps.build-static-image-os.outputs.tags }}
          registry: image-registry.apps.silver.devops.gov.bc.ca/1c4f9c-tools
          username: ${{ secrets.API_TOKEN_4 }}
          password: ${{ secrets.API_TOKEN_4 }}
      - name: Push Static To DockerHub Image repo
        id: push-to-docker-static
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-static-image-docker.outputs.image }}
          tags: ${{ steps.build-static-image-docker.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
