

# This is a basic workflow that will start a build with every push


name: CI/CD Runtests and build on Dev


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches: [ dev ]
    paths-ignore:
        - '.github/workflows/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} run Tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Install oc v3
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 3
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          # URL to your OpenShift cluster.
          # Refer to Step 2.
          openshift_server_url: ${{secrets.OCP4_SERVER_URL}}

          # Authentication Token. Can use username and password instead.
          # Refer to Step 3.
          openshift_token: ${{ secrets.API_TOKEN_4 }}

          # Disables SSL cert checking. Use this if you don't have the certificate authority data.
          insecure_skip_tls_verify: true

          # Optional - this sets your Kubernetes context's current namespace after logging in.
          namespace: ${{secrets.PROJECT_TOOLS_4}}
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: "https://github.com/bcgov/workbc-wage-subsidy.git#dev:packages/static"
#           push: true
#           tags: elmsd/workbc-wage-subsidy-v2-static:latest
      - name: Build for pushing to OpenShift registry
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: workbc-wage-subsidy-v2-static
          tags: latest
          context: ./packages/static
          containerfiles: ./packages/static/Dockerfile
          ref: dev
          tls-verify: false
          build-args: |
            VITE_REACT_ENVIRONMENT=Dev
      - name: Push To OpenShift Image repo
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: image-registry.apps.silver.devops.gov.bc.ca/1c4f9c-tools
#           username: ${{secrets.PROJECT_TOOLS_4}}
          password: ${{ secrets.API_TOKEN_4 }}
#       - name: OpenShift4 build Action
#         uses: redhat-developer/openshift-actions@v2.1.0
#         env:
#           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
#         with:
#           # Choose the oc version you want to use to execute the command. It can be a version or an url where to download oc cli desired. If left blank latest oc cli will be used.
#           version: latest
#           # The URL of the Openshift cluster
#           openshift_server_url: ${{secrets.OCP4_SERVER_URL}}
#           # JSON with values to connect to the Openshift cluster
#           parameters: '{"apitoken": "${{ secrets.API_TOKEN_4 }}", "acceptUntrustedCerts": "true"}'
#           # Oc command to be executed
#           cmd: |
#             'start-build workbc-wage-subsidy-v2-form-api -n ${{secrets.PROJECT_TOOLS_4}}'
#             'start-build workbc-wage-subsidy-v2-admin-api -n ${{secrets.PROJECT_TOOLS_4}}'
#             'start-build workbc-wage-subsidy-v2-employer-api -n ${{secrets.PROJECT_TOOLS_4}}'
#             'start-build workbc-wage-subsidy-v2-admin-client -n ${{secrets.PROJECT_TOOLS_4}}'
#             'start-build workbc-wage-subsidy-v2-employer-client -n ${{secrets.PROJECT_TOOLS_4}}'
#             'start-build workbc-wage-subsidy-v2-static -n ${{secrets.PROJECT_TOOLS_4}}'
